app:
  id: jDQUyibXNqElz2PbyivQVGrYbY

spring:
  application:
    name: blank-springboot

server:
  port: 8081

my:
  hello:
    name: "lee"
    age: 18
    hometown: "qf"


#单独控制某个包下的日志输出级别
#设置整个项目日志输出级别
logging:
  #设置一个组
  group:
    demo4: arthur.dy.lee
  level:
    root: info
    #com.fs包的日志输出级别为debug
    demo4: debug